#!/bin/bash

pushd catkin_ws
catkin config --install --no-extend
catkin build
popd

pushd overlay_ws
catkin config --extend ../catkin_ws/install
#source ../catkin_ws/install/setup.bash
catkin build
popd 
